### ISSUE TITLE
Cloning repository error

### ISSUE THREAD

**Issue by monooz23** [ordinals-wallet/ordinals-collections#2693]
Hi I keep getting this error when I try to clone the repository 

![image](https://github.com/ordinals-wallet/ordinals-collections/assets/125703133/090fc168-8606-46e4-b623-c015d7eedb23)

**Comment by monooz23** [comment]
![image](https://github.com/ordinals-wallet/ordinals-collections/assets/125703133/8412b156-a400-4673-b095-b0edd5190559)

**Comment by monooz23** [comment]
This seems to be causing cloning issues??

**Comment by monooz23** [comment]
and PR checks

**Comment by monooz23** [comment]
Is anyone else having this issue?

**Comment by aptcats** [comment]
> 

Me too, this is their problem and the update set will have 6 duplicate data

**Comment by kyosuke25** [comment]
I synchronized after I deleted it from my repo on Github website.
And then I committed it lol.
That folder has gone.
Sorry.

**Comment by kyosuke25** [comment]
@MillHaus33 
Could you fix it, please?

**Comment by monooz23** [comment]
still getting this?...any advice?
![image](https://github.com/ordinals-wallet/ordinals-collections/assets/125703133/42699153-f093-40c2-822b-975cdb6d70b7)

**Comment by monooz23** [comment]
@MillHaus33 

can you please help me here....

![image](https://github.com/ordinals-wallet/ordinals-collections/assets/125703133/05cb3079-b6d1-4b85-a138-16e9096152a3)

**Comment by monooz23** [comment]
@MillHaus33 
Hi bro,
can you help with this....
![image](https://github.com/ordinals-wallet/ordinals-collections/assets/125703133/b0f91a45-5433-4957-b968-13cb61b4b68d)

**Comment by cliobitcoinbank** [comment]
The folder name has to be your slug.  Maybe I'm missing something but check your folder heirchy and make sure it matches your slug and everything is in the right folders and the folders are named properly.
